<?php

namespace SiteTCH\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getAvecCategorie (array $nom_categories)
	{
		$qb =$this->createQueryBuilder('a');
		//On fait une jointure avec l'entité Categorie, avec pour alias c
		$qb->join('a.categories','c')
		//Puis on filtre sur le nom des catégories à l'aide d'un IN
		->where($qb->expr()->in('c.nom',$nom_categories));
		//Enfin, on retourne le résultat
		return $qb->getQuery()->getResult();
	}
	
	
}
