parameters:
#    site_tch_blog.example.class: SiteTCH\BlogBundle\Example

services:
#    site_tch_blog.example:
#        class: %site_tch_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
