parameters:
#    site_tch_user.example.class: SiteTCH\UserBundle\Example

services:
#    site_tch_user.example:
#        class: %site_tch_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
