<?php

namespace SiteGKT\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionRepository extends EntityRepository
{
}
