parameters:
#    site_tch_blog_abonne.example.class: SiteTCH\BlogAbonneBundle\Example

services:
#    site_tch_blog_abonne.example:
#        class: %site_tch_blog_abonne.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
